### ISSUE TITLE
tgt: Fail to find device occasionally 

### ISSUE THREAD

**Issue by yasker** [rancher/longhorn#231]
During teardown_test run.

```2016-11-02 20:20:16.634846: iteration = 10 thread = 11 : FAIL TO WAIT FOR DEVICE READY, docker logs:
time="2016-11-03T03:19:56Z" level=info msg="Starting with replicas [\"tcp://172.18.1.11:9502\" \"tcp://172.18.2.11:9502\"]"
time="2016-11-03T03:19:56Z" level=info msg="Connecting to remote: 172.18.1.11:9502"
time="2016-11-03T03:19:56Z" level=info msg="Opening: 172.18.1.11:9502"
time="2016-11-03T03:19:56Z" level=info msg="Adding backend: tcp://172.18.1.11:9502"
time="2016-11-03T03:19:56Z" level=info msg="Connecting to remote: 172.18.2.11:9502"
time="2016-11-03T03:19:56Z" level=info msg="Opening: 172.18.2.11:9502"
time="2016-11-03T03:19:56Z" level=info msg="Adding backend: tcp://172.18.2.11:9502"
time="2016-11-03T03:19:58Z" level=info msg="SCSI device /dev/sdf created"
time="2016-11-03T03:19:58Z" level=fatal msg="Failed to start up frontend: Cannot find /dev/sdf: no such file or directory"
Process Process-11:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "teardown-test.py", line 126, in run_test
    write_data(thread, pattern1)
  File "teardown-test.py", line 70, in write_data
    writeat_direct("/dev/longhorn/vol" + str(i), 0, str(chr(pattern))*PAGE_SIZE)
  File "teardown-test.py", line 55, in writeat_direct
    f = os.open(dev, os.O_DIRECT | os.O_RDWR)
OSError: [Errno 2] No such file or directory: '/dev/longhorn/vol11'
```

**Comment by yasker** [comment]
It's mostly likely because device isn't ready when we query for iscsiadm for device name. Need a retry mechanism there.
