### ISSUE TITLE
Cannot find device after reverting snapshot

### ISSUE THREAD

**Issue by sheng-liang** [rancher/longhorn#236]
2016-11-04 15:44:08.541778: iteration = 1 thread = 4 : Device ready after 2.220 seconds
2016-11-04 15:44:08.541864: iteration = 1 thread = 4 controller = 619d5a3c500dba645eb65a4c5a36a567500c881c970b23148199143837a2355a
<.... Many lines deleted ...>
2016-11-04 15:46:09.868969: iteration = 1 thread = 4 : FAIL TO WAIT FOR DEVICE READY, docker logs:
time="2016-11-04T22:44:06Z" level=info msg="Starting with replicas [\"tcp://172.18.1.4:9502\" \"tcp://172.18.2.4:9502\"]" 
time="2016-11-04T22:44:06Z" level=info msg="Connecting to remote: 172.18.1.4:9502" 
time="2016-11-04T22:44:06Z" level=info msg="Opening: 172.18.1.4:9502" 
time="2016-11-04T22:44:06Z" level=info msg="Adding backend: tcp://172.18.1.4:9502" 
time="2016-11-04T22:44:06Z" level=info msg="Connecting to remote: 172.18.2.4:9502" 
time="2016-11-04T22:44:06Z" level=info msg="Opening: 172.18.2.4:9502" 
time="2016-11-04T22:44:06Z" level=info msg="Adding backend: tcp://172.18.2.4:9502" 
time="2016-11-04T22:44:08Z" level=info msg="SCSI device /dev/sde created" 
time="2016-11-04T22:44:08Z" level=info msg="Creating device /dev/longhorn/vol4 8:64" 
time="2016-11-04T22:44:08Z" level=info msg="Device /dev/longhorn/vol4 is ready" 
time="2016-11-04T22:44:08Z" level=info msg="Listening on localhost:9501" 
time="2016-11-04T22:44:46Z" level=info msg="Snapshot: 172.18.2.4:9502 10e91896-f9a3-45f5-87c7-91a29fa82f8a" 
time="2016-11-04T22:44:46Z" level=info msg="Snapshot: 172.18.1.4:9502 10e91896-f9a3-45f5-87c7-91a29fa82f8a" 
127.0.0.1 - - [04/Nov/2016:22:44:46 +0000] "POST /v1/volumes/dm9sNA==?action=snapshot HTTP/1.1" 200 180
time="2016-11-04T22:45:48Z" level=info msg="Shutdown SCSI device for 172.18.0.2:iqn.2014-09.com.rancher:vol4" 
time="2016-11-04T22:45:49Z" level=info msg="Shutdown SCSI target iqn.2014-09.com.rancher:vol4" 
time="2016-11-04T22:45:49Z" level=info msg="Reverting to snapshot volume-snap-10e91896-f9a3-45f5-87c7-91a29fa82f8a.img on tcp://172.18.1.4:9502" 
time="2016-11-04T22:45:49Z" level=info msg="Reverting to snapshot volume-snap-10e91896-f9a3-45f5-87c7-91a29fa82f8a.img on tcp://172.18.2.4:9502" 
time="2016-11-04T22:45:49Z" level=warning msg="Socket server connection closed" 
time="2016-11-04T22:45:49Z" level=fatal msg="Failed to start up frontend: Failed to execute: tgtadm [--lld iscsi --op bind --mode target --tid 1 -I ALL], output tgtadm: failed to send request hdr to tgt daemon, Transport endpoint is not connected\n, error exit status 107" 
Process Process-4:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "teardown-test.py", line 162, in run_test
    check_data(thread, pattern1)
  File "teardown-test.py", line 76, in check_data
    data = readat_direct("/dev/longhorn/vol" + str(i), page * PAGE_SIZE, PAGE_SIZE)
  File "teardown-test.py", line 41, in readat_direct
    f = os.open(dev, os.O_DIRECT | os.O_RDONLY)
OSError: [Errno 2] No such file or directory: '/dev/longhorn/vol4'

**Comment by sheng-liang** [comment]
Another failure in the same setup, slightly different controller logs:

root@ubuntu:/home/sheng# docker logs 3b08fbc80b2e
time="2016-11-04T22:50:14Z" level=info msg="Starting with replicas [\"tcp://172.18.1.14:9502\" \"tcp://172.18.2.14:9502\"]" 
time="2016-11-04T22:50:14Z" level=info msg="Connecting to remote: 172.18.1.14:9502" 
time="2016-11-04T22:50:14Z" level=info msg="Opening: 172.18.1.14:9502" 
time="2016-11-04T22:50:14Z" level=info msg="Adding backend: tcp://172.18.1.14:9502" 
time="2016-11-04T22:50:14Z" level=info msg="Connecting to remote: 172.18.2.14:9502" 
time="2016-11-04T22:50:14Z" level=info msg="Opening: 172.18.2.14:9502" 
time="2016-11-04T22:50:14Z" level=info msg="Adding backend: tcp://172.18.2.14:9502" 
time="2016-11-04T22:50:17Z" level=info msg="SCSI device /dev/sdh created" 
time="2016-11-04T22:50:17Z" level=info msg="Creating device /dev/longhorn/vol14 8:112" 
time="2016-11-04T22:50:17Z" level=info msg="Device /dev/longhorn/vol14 is ready" 
time="2016-11-04T22:50:17Z" level=info msg="Listening on localhost:9501" 
time="2016-11-04T22:50:44Z" level=info msg="Snapshot: 172.18.2.14:9502 8f7ac338-ca1e-40d5-91a7-2cc80031c8af" 
time="2016-11-04T22:50:44Z" level=info msg="Snapshot: 172.18.1.14:9502 8f7ac338-ca1e-40d5-91a7-2cc80031c8af" 
127.0.0.1 - - [04/Nov/2016:22:50:44 +0000] "POST /v1/volumes/dm9sMTQ=?action=snapshot HTTP/1.1" 200 180
time="2016-11-04T22:51:50Z" level=info msg="Shutdown SCSI device for 172.18.0.14:iqn.2014-09.com.rancher:vol14" 
time="2016-11-04T22:51:51Z" level=info msg="Shutdown SCSI target iqn.2014-09.com.rancher:vol14" 
time="2016-11-04T22:51:51Z" level=info msg="Reverting to snapshot volume-snap-8f7ac338-ca1e-40d5-91a7-2cc80031c8af.img on tcp://172.18.1.14:9502" 
time="2016-11-04T22:51:51Z" level=info msg="Reverting to snapshot volume-snap-8f7ac338-ca1e-40d5-91a7-2cc80031c8af.img on tcp://172.18.2.14:9502" 
time="2016-11-04T22:51:51Z" level=warning msg="Socket server connection closed" 
panic: exit status 242

goroutine 77 [running]:
panic(0xa0bde0, 0xc4202f41e0)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/rancher/longhorn/vendor/github.com/yasker/go-iscsi-helper/iscsi.startDaemon(0xc420024390, 0x0)
	/go/src/github.com/rancher/longhorn/vendor/github.com/yasker/go-iscsi-helper/iscsi/target.go:193 +0xfd
created by github.com/rancher/longhorn/vendor/github.com/yasker/go-iscsi-helper/iscsi.StartDaemon
	/go/src/github.com/rancher/longhorn/vendor/github.com/yasker/go-iscsi-helper/iscsi/target.go:163 +0x87

**Comment by sheng-liang** [comment]
Similar failure, this time with tgtd.log:

First, test output:
2016-11-04 15:54:28.182771: iteration = 4 thread = 11 : FAIL TO WAIT FOR DEVICE READY, docker logs:
time="2016-11-04T22:52:27Z" level=info msg="Starting with replicas [\"tcp://172.18.1.11:9502\" \"tcp://172.18.2.11:9502\"]" 
time="2016-11-04T22:52:27Z" level=info msg="Connecting to remote: 172.18.1.11:9502" 
time="2016-11-04T22:52:27Z" level=info msg="Opening: 172.18.1.11:9502" 
time="2016-11-04T22:52:27Z" level=info msg="Adding backend: tcp://172.18.1.11:9502" 
time="2016-11-04T22:52:27Z" level=info msg="Connecting to remote: 172.18.2.11:9502" 
time="2016-11-04T22:52:27Z" level=info msg="Opening: 172.18.2.11:9502" 
time="2016-11-04T22:52:27Z" level=info msg="Adding backend: tcp://172.18.2.11:9502" 
time="2016-11-04T22:52:29Z" level=info msg="SCSI device /dev/sdb created" 
time="2016-11-04T22:52:29Z" level=info msg="Creating device /dev/longhorn/vol11 8:16" 
time="2016-11-04T22:52:29Z" level=info msg="Device /dev/longhorn/vol11 is ready" 
time="2016-11-04T22:52:29Z" level=info msg="Listening on localhost:9501" 
time="2016-11-04T22:52:50Z" level=info msg="Snapshot: 172.18.2.11:9502 a2ceb554-4e50-45f1-8e62-ef5fafeedffa" 
time="2016-11-04T22:52:50Z" level=info msg="Snapshot: 172.18.1.11:9502 a2ceb554-4e50-45f1-8e62-ef5fafeedffa" 
127.0.0.1 - - [04/Nov/2016:22:52:50 +0000] "POST /v1/volumes/dm9sMTE=?action=snapshot HTTP/1.1" 200 180
time="2016-11-04T22:54:07Z" level=info msg="Shutdown SCSI device for 172.18.0.11:iqn.2014-09.com.rancher:vol11" 
time="2016-11-04T22:54:07Z" level=info msg="Shutdown SCSI target iqn.2014-09.com.rancher:vol11" 
time="2016-11-04T22:54:07Z" level=info msg="Reverting to snapshot volume-snap-a2ceb554-4e50-45f1-8e62-ef5fafeedffa.img on tcp://172.18.1.11:9502" 
time="2016-11-04T22:54:07Z" level=info msg="Reverting to snapshot volume-snap-a2ceb554-4e50-45f1-8e62-ef5fafeedffa.img on tcp://172.18.2.11:9502" 
panic: exit status 242

goroutine 84 [running]:
panic(0xa0bde0, 0xc420205840)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/rancher/longhorn/vendor/github.com/yasker/go-iscsi-helper/iscsi.startDaemon(0xc420308028, 0x0)
	/go/src/github.com/rancher/longhorn/vendor/github.com/yasker/go-iscsi-helper/iscsi/target.go:193 +0xfd
created by github.com/rancher/longhorn/vendor/github.com/yasker/go-iscsi-helper/iscsi.StartDaemon
	/go/src/github.com/rancher/longhorn/vendor/github.com/yasker/go-iscsi-helper/iscsi/target.go:163 +0x87
Process Process-11:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "teardown-test.py", line 162, in run_test
    check_data(thread, pattern1)
  File "teardown-test.py", line 76, in check_data
    data = readat_direct("/dev/longhorn/vol" + str(i), page * PAGE_SIZE, PAGE_SIZE)
  File "teardown-test.py", line 41, in readat_direct
    f = os.open(dev, os.O_DIRECT | os.O_RDONLY)
OSError: [Errno 2] No such file or directory: '/dev/longhorn/vol11'

Next, docker log:

sheng@ubuntu:~$ docker logs f0
time="2016-11-04T22:52:27Z" level=info msg="Starting with replicas [\"tcp://172.18.1.11:9502\" \"tcp://172.18.2.11:9502\"]" 
time="2016-11-04T22:52:27Z" level=info msg="Connecting to remote: 172.18.1.11:9502" 
time="2016-11-04T22:52:27Z" level=info msg="Opening: 172.18.1.11:9502" 
time="2016-11-04T22:52:27Z" level=info msg="Adding backend: tcp://172.18.1.11:9502" 
time="2016-11-04T22:52:27Z" level=info msg="Connecting to remote: 172.18.2.11:9502" 
time="2016-11-04T22:52:27Z" level=info msg="Opening: 172.18.2.11:9502" 
time="2016-11-04T22:52:27Z" level=info msg="Adding backend: tcp://172.18.2.11:9502" 
time="2016-11-04T22:52:29Z" level=info msg="SCSI device /dev/sdb created" 
time="2016-11-04T22:52:29Z" level=info msg="Creating device /dev/longhorn/vol11 8:16" 
time="2016-11-04T22:52:29Z" level=info msg="Device /dev/longhorn/vol11 is ready" 
time="2016-11-04T22:52:29Z" level=info msg="Listening on localhost:9501" 
time="2016-11-04T22:52:50Z" level=info msg="Snapshot: 172.18.2.11:9502 a2ceb554-4e50-45f1-8e62-ef5fafeedffa" 
time="2016-11-04T22:52:50Z" level=info msg="Snapshot: 172.18.1.11:9502 a2ceb554-4e50-45f1-8e62-ef5fafeedffa" 
127.0.0.1 - - [04/Nov/2016:22:52:50 +0000] "POST /v1/volumes/dm9sMTE=?action=snapshot HTTP/1.1" 200 180
time="2016-11-04T22:54:07Z" level=info msg="Shutdown SCSI device for 172.18.0.11:iqn.2014-09.com.rancher:vol11" 
time="2016-11-04T22:54:07Z" level=info msg="Shutdown SCSI target iqn.2014-09.com.rancher:vol11" 
time="2016-11-04T22:54:07Z" level=info msg="Reverting to snapshot volume-snap-a2ceb554-4e50-45f1-8e62-ef5fafeedffa.img on tcp://172.18.1.11:9502" 
time="2016-11-04T22:54:07Z" level=info msg="Reverting to snapshot volume-snap-a2ceb554-4e50-45f1-8e62-ef5fafeedffa.img on tcp://172.18.2.11:9502" 
panic: exit status 242

goroutine 84 [running]:
panic(0xa0bde0, 0xc420205840)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/rancher/longhorn/vendor/github.com/yasker/go-iscsi-helper/iscsi.startDaemon(0xc420308028, 0x0)
	/go/src/github.com/rancher/longhorn/vendor/github.com/yasker/go-iscsi-helper/iscsi/target.go:193 +0xfd
created by github.com/rancher/longhorn/vendor/github.com/yasker/go-iscsi-helper/iscsi.StartDaemon
	/go/src/github.com/rancher/longhorn/vendor/github.com/yasker/go-iscsi-helper/iscsi/target.go:163 +0x87

Finally, tgtd.log:

sheng@ubuntu:~$ cat var/log/tgtd.log 
tgtd: iser_ib_init(3431) Failed to initialize RDMA; load kernel modules?
tgtd: work_timer_start(146) use timer_fd based scheduler
tgtd: bs_init(387) use signalfd notification
tgtd: device_mgmt(246) sz:70 params:path=/var/run/longhorn-vol11.sock,bstype=longhorn,bsopts=size=1048576
tgtd: bs_thread_open(409) 16
tgtd: bs_longhorn_request(101) cmd->scb[0]: 35
tgtd: device_mgmt(246) sz:70 params:path=/var/run/longhorn-vol11.sock,bstype=longhorn,bsopts=size=1048576
tgtd: bs_thread_open(409) 16
connect error: No such file or directory
