### ISSUE TITLE
Index out of range error during test_teardown.py run

### ISSUE THREAD

**Issue by yasker** [rancher/longhorn#240]
```
2016-11-06 01:54:17.598079: iteration = 651 thread = 18 : Device ready after 1.708 seconds
2016-11-06 01:54:17.598158: iteration = 651 thread = 18 controller = fd82291d5695d669d087228ff2dffa16244a69d9d4ceb8556386c83359caa147
2016-11-06 01:54:19.649708: iteration = 643 thread = 13 : Device ready after 1.659 seconds
2016-11-06 01:54:19.650405: iteration = 643 thread = 13 controller = 2ef0b33c8a3e521e4df2f6b96988767a6d0f313b0d318c3cc501cd268b948f33
2016-11-06 01:54:20.946196: iteration = 648 thread = 20 : Device ready after 0.000 seconds
9b75e7487c73f540cb3be729788a3d2c78ce6a0a9648972d2844b1748b380571
2016-11-06 01:54:21.889496: iteration = 642 thread = 16 : Device deleted after 0.000 seconds
ca37ae87b609be1ed2e4b3f4c252c771741015e01b79392b1f4f973b5388b503
64f73d358824db43292dff67c28b137fbd2a8e6b4d307b7db250d63337460c7d
9b75e7487c73f540cb3be729788a3d2c78ce6a0a9648972d2844b1748b380571
ca37ae87b609be1ed2e4b3f4c252c771741015e01b79392b1f4f973b5388b503
64f73d358824db43292dff67c28b137fbd2a8e6b4d307b7db250d63337460c7d
2016-11-06 01:54:22.825067: iteration = 643 thread = 16 replica1 = 00159b3e65f40bad57b44a417cdf6de3f70cb5eb7b3b30ef45202b6c65e72a64
2016-11-06 01:54:23.186367: iteration = 643 thread = 16 replica2 = 436f04be0b65dd59f880bb60d93ec24454455a7cb2ded502ef9d756588583f29
2016-11-06 01:54:23.976596: iteration = 646 thread = 17 : Device ready after 1.606 seconds
2016-11-06 01:54:23.976666: iteration = 646 thread = 17 controller = 502aece3dbe90d4e69f974ccd1239009ba3df799d9fc731142cf0296c0e7e079
78874763e524491dc063aebeaf9b036d34bb9615eeb11d2283ea6b47aae82948
2016-11-06 01:54:24.894849: iteration = 648 thread = 11 : Device deleted after 0.000 seconds
0fe18a0b45714975243f519b07e06c63988f264e7f527a4e66fce7a48fd1837b
070bd1ea36d85c476c1648076b4c4a3a396a21c65c9a5b105cc61bf444147d83
78874763e524491dc063aebeaf9b036d34bb9615eeb11d2283ea6b47aae82948
0fe18a0b45714975243f519b07e06c63988f264e7f527a4e66fce7a48fd1837b
070bd1ea36d85c476c1648076b4c4a3a396a21c65c9a5b105cc61bf444147d83
2016-11-06 01:54:25.878460: iteration = 649 thread = 11 replica1 = c8a4834cf7225f09d92ff74d5788366837b2fdef1f7d0c325004788725428539
2016-11-06 01:54:26.256689: iteration = 649 thread = 11 replica2 = 42e784516a5f8f0dee0d2241ab930e37f029fd9766bb7d0e72390b671209ba57
2016-11-06 01:54:26.986346: iteration = 642 thread = 15 : Device ready after 1.658 seconds
2016-11-06 01:54:26.986437: iteration = 642 thread = 15 controller = 913ebc0543717777530706cdf0b879407ed6c0bb74b6b71e9f9704d144ec2f7c
a3ffd3cafba2520504ba4a05e3514d27db26e69725f5867691ba796154b5293e
2016-11-06 01:54:27.884063: iteration = 645 thread = 19 : Device deleted after 0.000 seconds
e47da454502bf049b11e2f1ca650046bfa2bc487924dbe7ed0deb51b6f5f9f10
4c21c18ce511f22876cc1d1bd09ab13e71c8a4d33cd8ac0618c295422e780f6e
a3ffd3cafba2520504ba4a05e3514d27db26e69725f5867691ba796154b5293e
e47da454502bf049b11e2f1ca650046bfa2bc487924dbe7ed0deb51b6f5f9f10
4c21c18ce511f22876cc1d1bd09ab13e71c8a4d33cd8ac0618c295422e780f6e
2016-11-06 01:54:28.886037: iteration = 646 thread = 19 replica1 = ddd991807b71aa2c66d4c6ef06a99920d5bd92bf42e7a315d9d70dbb08b90314
2016-11-06 01:54:29.255955: iteration = 646 thread = 19 replica2 = a499a6b04be8da684c346cd9e8e2a2781415bd5dcebc2b1f6a015531c7e9e023
2016-11-06 01:54:29.983437: iteration = 640 thread = 14 : Device ready after 1.657 seconds
2016-11-06 01:54:29.983514: iteration = 640 thread = 14 controller = 73e21005f51d333c8a5a3d8e08f58f2bedaec48271e69e2c9fb9dd4c5b158826
2016-11-06 01:54:32.086427: iteration = 640 thread = 10 : Device ready after 1.709 seconds
2016-11-06 01:54:32.086498: iteration = 640 thread = 10 controller = b9d7bd005219df541c314acb2205475dd13e2df71a3e0735b1b113ef1c619572
2016-11-06 01:54:33.357350: iteration = 644 thread = 8 : Device ready after 0.000 seconds
52e34e63c6989e7151386e75480689262bebb3a06322c452d304291d82a81356
2016-11-06 01:54:34.263080: iteration = 640 thread = 7 : Device deleted after 0.000 seconds
3f6cdb9463df1f457b6653cdf9e3535d5222936509a2bf77706d3db9b5b37825
de78aa82135acb4398759b9b4759221950b7c4f0a4445233f740a57514344141
52e34e63c6989e7151386e75480689262bebb3a06322c452d304291d82a81356
3f6cdb9463df1f457b6653cdf9e3535d5222936509a2bf77706d3db9b5b37825
de78aa82135acb4398759b9b4759221950b7c4f0a4445233f740a57514344141
88319eb791759452221c34117535205dae285f8452d11a537160c3a65ad71e3f
2016-11-06 01:54:35.137965: iteration = 645 thread = 4 : Device deleted after 0.000 seconds
2016-11-06 01:54:35.490759: iteration = 641 thread = 7 replica1 = dfb3b40a01cb4822285cf2ef9fbc2f682b3e7996cc3c96419781544bb48e7133
35a77a9d00dc66101a912ec2ce732b24f92003f5a7a66d0f92c35e643909ba41
272eb12fffcc6a4129cdd6f8b4ca4d7c1a5e7d7999ce1838f0b80cc1beb5593f
88319eb791759452221c34117535205dae285f8452d11a537160c3a65ad71e3f
35a77a9d00dc66101a912ec2ce732b24f92003f5a7a66d0f92c35e643909ba41
272eb12fffcc6a4129cdd6f8b4ca4d7c1a5e7d7999ce1838f0b80cc1beb5593f
2016-11-06 01:54:36.003919: iteration = 641 thread = 7 replica2 = 4bcb75e6c8da13760da663d7cb45e701e778707755dd721c2a2b5093791a8042
2f89427aa6180617f9a532a959eb2f3452f337b0d53d2e1e5476cc483892882e
2016-11-06 01:54:36.077647: iteration = 644 thread = 6 : Device deleted after 0.000 seconds
1e4a5802a9e94d4162c0de2aa423171d446406d0d05ed149d72ebd499134723b
3b1d23e808d52452996b32e21c0a551744c8cb692ed5cf22c4f51d84b204355b
2f89427aa6180617f9a532a959eb2f3452f337b0d53d2e1e5476cc483892882e
1e4a5802a9e94d4162c0de2aa423171d446406d0d05ed149d72ebd499134723b
3b1d23e808d52452996b32e21c0a551744c8cb692ed5cf22c4f51d84b204355b
2016-11-06 01:54:36.768359: iteration = 646 thread = 4 replica1 = 8aed77eb854e6060583a20ef1e772a0f78e5e2160fdec62aa8758ba803bbfe48
df9543756c312d27f05e1979c2cd85224aef78da747b802dd817fe5c81c80f7a
2016-11-06 01:54:37.012044: iteration = 646 thread = 5 : Device deleted after 0.000 seconds
b08cec4c073beb5ff6f2a1df2433961845a535ce8e0962642984aa0549672e64
2016-11-06 01:54:37.559644: iteration = 646 thread = 4 replica2 = 7f0a28428437a965847aa3e5af8bb039b955f8bc2d012308b16ace7fb10f4a25
2016-11-06 01:54:37.618571: iteration = 645 thread = 6 replica1 = 2cf08216bb845e20e6311b6ef8c32f69275402970d0a553a100f64f5e4057a37
ce08ac8e0aeb0163e55bdc088866cb2f5691027bfb8bc050aafa8f1ec92b001c
df9543756c312d27f05e1979c2cd85224aef78da747b802dd817fe5c81c80f7a
b08cec4c073beb5ff6f2a1df2433961845a535ce8e0962642984aa0549672e64
ce08ac8e0aeb0163e55bdc088866cb2f5691027bfb8bc050aafa8f1ec92b001c
57006a1538decf47ef163d9186770a2f7d2bbae8d2a11d419f50bc7e23a59311
2016-11-06 01:54:37.970079: iteration = 644 thread = 12 : Device deleted after 0.000 seconds
2016-11-06 01:54:38.212691: iteration = 645 thread = 6 replica2 = 1c562b12c35f3f624d173237d70a75423bf042a1510be43cae85bc09ac284203
2016-11-06 01:54:38.315539: iteration = 647 thread = 5 replica1 = 90f213a648bd822c0f7b52983345bc33850c8760258258555cff1128bcfde23d
c0c3658a74d9fa78b07e0940534ca0147c606e4ba996a27732e5c5486d2e8227
2bbce156c3cef06d79bc24598b910c7dbedfe77f43528836a4e4fd96bdc7b021
57006a1538decf47ef163d9186770a2f7d2bbae8d2a11d419f50bc7e23a59311
c0c3658a74d9fa78b07e0940534ca0147c606e4ba996a27732e5c5486d2e8227
2bbce156c3cef06d79bc24598b910c7dbedfe77f43528836a4e4fd96bdc7b021
2016-11-06 01:54:38.759044: iteration = 647 thread = 5 replica2 = 400d1e8d8fb2ea250977e9e7d792e82a114972c00445ae401a83705140337651
2016-11-06 01:54:39.010553: iteration = 645 thread = 12 replica1 = edec62a43cf6806af65361188c09bc254fa18a0d60a0d37e4e682ac95fb1643c
2016-11-06 01:54:39.279605: iteration = 647 thread = 1 : Device ready after 0.000 seconds
2016-11-06 01:54:39.419588: iteration = 645 thread = 12 replica2 = 3bf36e158d48c40e7b87b0031c99852af931bbcc1b5e737f95b0af87b2047f02
41526cf4e1b1c37ec3f064b7a2331c53665d8f362364bb1b24c4ac524713df66
2016-11-06 01:54:40.186602: iteration = 644 thread = 2 : Device deleted after 0.000 seconds
8d4c98f9e454785e56959748f968f6589a9a4d63b1c12720139134a1dd57cb12
342adb8860064f70142b83ab6ac92379bd0f5b090de83132597de96868564e05
41526cf4e1b1c37ec3f064b7a2331c53665d8f362364bb1b24c4ac524713df66
8d4c98f9e454785e56959748f968f6589a9a4d63b1c12720139134a1dd57cb12
342adb8860064f70142b83ab6ac92379bd0f5b090de83132597de96868564e05
2016-11-06 01:54:41.141256: iteration = 645 thread = 2 replica1 = 48cd0330d5c64603b27d753f0e5a890ed58773019c2c753129d3b1bbb060f626
2016-11-06 01:54:41.525097: iteration = 645 thread = 2 replica2 = b086e4fe4d543517f7a22edf8b6bdb2e7fd2bf08c0110c07e9ec75360a9c580c
2016-11-06 01:54:42.280092: iteration = 647 thread = 3 : Device ready after 1.708 seconds
2016-11-06 01:54:42.280185: iteration = 647 thread = 3 controller = 99e36e9dc90f7240ee8020e808643d61e07f76874a78247ac5aef2ded837e320
2016-11-06 01:54:44.273103: iteration = 647 thread = 9 : Device ready after 1.606 seconds
2016-11-06 01:54:44.273186: iteration = 647 thread = 9 controller = 5e5c5dda37bbbb7ce97fcaf878d611307fba1d14f9c9196a08fed2728a44cd2d
panic: runtime error: index out of range

goroutine 1 [running]:
panic(0x9a93a0, 0xc420012090)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/rancher/longhorn/app.revertSnapshot(0xc42008fa40, 0xc4201c5af8, 0x48d941)
        /go/src/github.com/rancher/longhorn/app/snapshot.go:96 +0x106
github.com/rancher/longhorn/app.SnapshotRevertCmd.func1(0xc42008fa40)
        /go/src/github.com/rancher/longhorn/app/snapshot.go:48 +0x2f
github.com/rancher/longhorn/vendor/github.com/codegangsta/cli.Command.Run(0xa2eae3, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/rancher/longhorn/vendor/github.com/codegangsta/cli/command.go:179 +0xbbe
github.com/rancher/longhorn/vendor/github.com/codegangsta/cli.(*App).RunAsSubcommand(0xc4200769a0, 0xc42008f7c0, 0x0, 0x0)
        /go/src/github.com/rancher/longhorn/vendor/github.com/codegangsta/cli/app.go:307 +0x9fb
github.com/rancher/longhorn/vendor/github.com/codegangsta/cli.Command.startApp(0xa30154, 0x9, 0xa2f92c, 0x8, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/rancher/longhorn/vendor/github.com/codegangsta/cli/command.go:261 +0x7ac
github.com/rancher/longhorn/vendor/github.com/codegangsta/cli.Command.Run(0xa30154, 0x9, 0xa2f92c, 0x8, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/rancher/longhorn/vendor/github.com/codegangsta/cli/command.go:70 +0x16a3
github.com/rancher/longhorn/vendor/github.com/codegangsta/cli.(*App).Run(0xc420076840, 0xc42000c0f0, 0x3, 0x3, 0x0, 0x0)
        /go/src/github.com/rancher/longhorn/vendor/github.com/codegangsta/cli/app.go:196 +0xc00
main.longhornCli()
        /go/src/github.com/rancher/longhorn/main.go:77 +0x5a4
main.main()
        /go/src/github.com/rancher/longhorn/main.go:24 +0xac
2016-11-06 01:54:44.374545: iteration = 651 thread = 18 : Device ready after 0.000 seconds
Process Process-18:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "teardown-test.py", line 162, in run_test
    check_data(thread, pattern1)
  File "teardown-test.py", line 77, in check_data
    assert ord(data[0]) == pattern
AssertionError
```
controller log:
```
yasker@ubuntu:~$ docker logs fd82291d5695
time="2016-11-06T08:54:15Z" level=info msg="Starting with replicas [\"tcp://172.18.1.18:9502\" \"tcp://172.18.2.18:9502\"]" 
time="2016-11-06T08:54:15Z" level=info msg="Connecting to remote: 172.18.1.18:9502" 
time="2016-11-06T08:54:15Z" level=info msg="Opening: 172.18.1.18:9502" 
time="2016-11-06T08:54:15Z" level=info msg="Adding backend: tcp://172.18.1.18:9502" 
time="2016-11-06T08:54:15Z" level=info msg="Connecting to remote: 172.18.2.18:9502" 
time="2016-11-06T08:54:15Z" level=info msg="Opening: 172.18.2.18:9502" 
time="2016-11-06T08:54:15Z" level=info msg="Adding backend: tcp://172.18.2.18:9502" 
time="2016-11-06T08:54:17Z" level=info msg="SCSI device /dev/sdg created" 
time="2016-11-06T08:54:17Z" level=info msg="Creating device /dev/longhorn/vol18 8:96" 
time="2016-11-06T08:54:17Z" level=info msg="Device /dev/longhorn/vol18 is ready" 
time="2016-11-06T08:54:17Z" level=info msg="Listening on localhost:9501" 
time="2016-11-06T08:54:17Z" level=info msg="Snapshot: 172.18.2.18:9502 4ad6d729-3c15-4a0d-a436-5700269c01ac" 
time="2016-11-06T08:54:17Z" level=info msg="Snapshot: 172.18.1.18:9502 4ad6d729-3c15-4a0d-a436-5700269c01ac" 
127.0.0.1 - - [06/Nov/2016:08:54:17 +0000] "POST /v1/volumes/dm9sMTg=?action=snapshot HTTP/1.1" 200 180
```

**Comment by yasker** [comment]
Update teardown_test to prevent empty snapshot.
