### ISSUE TITLE
Enforce snapshot maximum counts to 254

### ISSUE THREAD

**Issue by yasker** [rancher/longhorn#251]
Triggered by the fix of #247.

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x548784]

goroutine 4884 [running]:
panic(0x9a5f80, 0xc420012050)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/rancher/longhorn/replica.(*diffDisk).fullWriteAt(0xc4200b6108, 0xc42040a000, 0x100000, 0x100000, 0x13e00000, 0xc420018ea8, 0xc4200b6100, 0xffffffff)
	/go/src/github.com/rancher/longhorn/replica/diff_disk.go:101 +0xf4
github.com/rancher/longhorn/replica.(*diffDisk).WriteAt(0xc4200b6108, 0xc42040a000, 0x100000, 0x100000, 0x13e00000, 0x452270, 0xc420018f10, 0xc420018f18)
	/go/src/github.com/rancher/longhorn/replica/diff_disk.go:49 +0x35f
github.com/rancher/longhorn/replica.(*Replica).WriteAt(0xc4200b60f0, 0xc42040a000, 0x100000, 0x100000, 0x13e00000, 0x100000, 0x0, 0xc42024a000)
	/go/src/github.com/rancher/longhorn/replica/replica.go:775 +0xe5
github.com/rancher/longhorn/replica.(*Server).WriteAt(0xc4200456c0, 0xc42040a000, 0x100000, 0x100000, 0x13e00000, 0x0, 0x0, 0x0)
	/go/src/github.com/rancher/longhorn/replica/server.go:246 +0xbb
github.com/rancher/longhorn/rpc.(*Server).handleWrite(0xc420271080, 0xc42024a050)
	/go/src/github.com/rancher/longhorn/rpc/server.go:82 +0x61
created by github.com/rancher/longhorn/rpc.(*Server).readFromWire
	/go/src/github.com/rancher/longhorn/rpc/server.go:49 +0xf9

**Comment by yasker** [comment]
Found it's due to the snapshot counts are 257 in the situation, which exceeds one byte's maximum.

**Comment by yasker** [comment]
Need to find a way to communicate backend to frontend about how many snapshots are available to be taken as well, otherwise controller will blinding mark replica as error since it refused to take more snapshots.

**Comment by yasker** [comment]
Fixed at: https://github.com/rancher/longhorn/commit/868fc8aa5a9e1cd90db24ac697b9a40594b12e1b
