### ISSUE TITLE
"More than one head volume found" during snapshot, from rebuild_test

### ISSUE THREAD

**Issue by yasker** [rancher/longhorn#261]
Seems like a race condition can happen when snapshot is happening during rebuilding process.

```
time="2016-12-20T22:20:36Z" level=info msg="Done synchronizing volume-snap-97a39157-2aa9-4d7d-b05c-cf2a010e59cb.img to volume-snap-97a39157-2aa9-4d7d-b05c-cf2a010e59cb.img@172.18.1.10:9708" 
time="2016-12-20T22:20:36Z" level=info msg="Synchronizing volume-snap-97a39157-2aa9-4d7d-b05c-cf2a010e59cb.img.meta to volume-snap-97a39157-2aa9-4d7d-b05c-cf2a010e59cb.img.meta@172.18.1.10:9709" 
time="2016-12-20T22:20:36Z" level=info msg="Coalescing volume-snap-c83ab0ad-7f8e-4187-8b56-88fa503ac362.img to volume-snap-b8ab7a99-8cd3-4120-9d04-60b9205905fa.img on tcp://172.18.2.4:9502" 
83bdcf5016d41c4584af6094d5a6596e43392040f2394f38f2d986a07117a705
time="2016-12-20T22:20:36Z" level=info msg="Done synchronizing volume-snap-97a39157-2aa9-4d7d-b05c-cf2a010e59cb.img.meta to volume-snap-97a39157-2aa9-4d7d-b05c-cf2a010e59cb.img.meta@172.18.1.10:9709" 
time="2016-12-20T22:20:36Z" level=fatal msg="Error running add replica command: More than one head volume found in the from replica volume-head-001.img, volume-head-009.img" 
Failed to delete 0be70e22-f56a-44a1-8fda-13ab74a95625: Can not remove a snapshot because tcp://172.18.1.10:9502 is rebuilding
time="2016-12-20T22:20:37Z" level=fatal msg="Error running rm snapshot command: Can not remove a snapshot because tcp://172.18.1.10:9502 is rebuilding" 
Process Process-10:1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "rebuild-test.py", line 143, in rebuild_replicas
    " longhorn snapshots rm " + snapshot, shell=True)
  File "/usr/lib/python2.7/subprocess.py", line 574, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
CalledProcessError: Command 'docker exec 166b67b72c1e445a3be56b055729c246f74c20b508b3fe03aa15e52c9d03ee31 longhorn snapshots rm 0be70e22-f56a-44a1-8fda-13ab74a95625' returned non-zero exit status 1
```

**Comment by yasker** [comment]
Also found in:

```
time="2016-12-22T01:09:51Z" level=fatal msg="Error running add replica command: More than one head volume found in the from replica volume-head-007.img, volume-head-001.img" 
2016-12-21 17:09:51.353357: thread = 1 iteration = 16 current snapshot counts 1
Process Process-9:1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
2016-12-21 17:09:51.355586: thread = 3 iteration = 12 current snapshot counts 6
2016-12-21 17:09:51.355858: thread = 4 iteration = 12 current snapshot counts 1
2016-12-21 17:09:51.357177: thread = 8 iteration = 11 current snapshot counts 2
2016-12-21 17:09:51.357826: thread = 2 iteration = 32 current snapshot counts 17
2016-12-21 17:09:51.360068: thread = 9 iteration = 11 current snapshot counts 4
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "rebuild-test.py", line 138, in rebuild_replicas
    replica2 = rebuild_replica(thread, controller, 2, replica2)
  File "rebuild-test.py", line 121, in rebuild_replica
    subprocess.check_call(("docker exec " + controller + " longhorn add tcp://" + replica_host_port).split())
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
2016-12-21 17:09:51.362058: thread = 5 iteration = 8 current snapshot counts 1
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command '['docker', 'exec', 'ac38f9a978b9ed680c40dc3952a0c67d189cb030a7f09b41007e400e05facb3b', 'longhorn', 'add', 'tcp://172.18.2.9:9502']' returned non-zero exit status 1
```

**Comment by yasker** [comment]
Fixed by:

commit 926f3be76597767d1cc4d5c0d254e60d95441f0e
Author: Sheng Yang <sheng@yasker.org>
Date:   Wed Dec 21 18:44:04 2016 -0800

    sync: Determine the volume head by looking into chain
    
    Rather than looking into all the present disks, since there is a gap between
    create the new head and remove the old head, which means there can be two heads
    in the same replica for a brief moment. Better check the chain for who's current
    head.
