### ISSUE TITLE
invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by andreastoermer** [rancher/longhorn#264]
After updating an existing longhorn installation on my rancher 2.0.7 cluster i get the following log output. With the old longhorn version everything works. Have somebody an idea?

`E0827 10:26:36.307611 1 runtime.go:66] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
/go/src/github.com/rancher/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:72
/go/src/github.com/rancher/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65
/go/src/github.com/rancher/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51
/usr/local/go/src/runtime/asm_amd64.s:509
/usr/local/go/src/runtime/panic.go:491
/usr/local/go/src/runtime/panic.go:63
/usr/local/go/src/runtime/signal_unix.go:367
<autogenerated>:1
/go/src/github.com/rancher/longhorn-manager/vendor/k8s.io/client-go/tools/cache/store.go:84
/go/src/github.com/rancher/longhorn-manager/vendor/k8s.io/client-go/tools/cache/controller.go:261
/go/src/github.com/rancher/longhorn-manager/controller/node_controller.go:336
/go/src/github.com/rancher/longhorn-manager/controller/node_controller.go:363
/go/src/github.com/rancher/longhorn-manager/controller/node_controller.go:151
/go/src/github.com/rancher/longhorn-manager/vendor/k8s.io/client-go/tools/cache/controller.go:195
<autogenerated>:1
/go/src/github.com/rancher/longhorn-manager/vendor/k8s.io/client-go/tools/cache/controller.go:227
<autogenerated>:1
/go/src/github.com/rancher/longhorn-manager/vendor/k8s.io/client-go/tools/cache/shared_informer.go:554
/go/src/github.com/rancher/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:203
/go/src/github.com/rancher/longhorn-manager/vendor/k8s.io/client-go/tools/cache/shared_informer.go:548
/go/src/github.com/rancher/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133
/go/src/github.com/rancher/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134
/go/src/github.com/rancher/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88
/go/src/github.com/rancher/longhorn-manager/vendor/k8s.io/client-go/tools/cache/shared_informer.go:546
/go/src/github.com/rancher/longhorn-manager/vendor/k8s.io/client-go/tools/cache/shared_informer.go:390
/go/src/github.com/rancher/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:71
/usr/local/go/src/runtime/asm_amd64.s:2337
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1117b95]
goroutine 185 [running]:
github.com/rancher/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
/go/src/github.com/rancher/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x111
panic(0x13f5fe0, 0x2166f30)
/usr/local/go/src/runtime/panic.go:491 +0x283
github.com/rancher/longhorn-manager/k8s/pkg/apis/longhorn/v1alpha1.(*Node).GetNamespace(0x0, 0x0, 0x7f77002c5160)
<autogenerated>:1 +0x5
github.com/rancher/longhorn-manager/vendor/k8s.io/client-go/tools/cache.MetaNamespaceKeyFunc(0x1576e00, 0x0, 0x8, 0xc42017d0e0, 0x194, 0xc420569b50)
/go/src/github.com/rancher/longhorn-manager/vendor/k8s.io/client-go/tools/cache/store.go:84 +0x132
github.com/rancher/longhorn-manager/vendor/k8s.io/client-go/tools/cache.DeletionHandlingMetaNamespaceKeyFunc(0x1576e00, 0x0, 0x8, 0xc420569bb0, 0x112fa63, 0x217d380)
/go/src/github.com/rancher/longhorn-manager/vendor/k8s.io/client-go/tools/cache/controller.go:261 +0x74
github.com/rancher/longhorn-manager/controller.(*NodeController).enqueueNode(0xc420092990, 0x0)
/go/src/github.com/rancher/longhorn-manager/controller/node_controller.go:336 +0x48
github.com/rancher/longhorn-manager/controller.(*NodeController).enqueueReplica(0xc420092990, 0xc4208c0ee0)
/go/src/github.com/rancher/longhorn-manager/controller/node_controller.go:363 +0xf5
github.com/rancher/longhorn-manager/controller.NewNodeController.func8(0x15770c0, 0xc4208c0ee0)
/go/src/github.com/rancher/longhorn-manager/controller/node_controller.go:151 +0x45
github.com/rancher/longhorn-manager/vendor/k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnAdd(0xc420386310, 0xc420386320, 0xc420386330, 0x15770c0, 0xc4208c0ee0)
/go/src/github.com/rancher/longhorn-manager/vendor/k8s.io/client-go/tools/cache/controller.go:195 +0x49
github.com/rancher/longhorn-manager/vendor/k8s.io/client-go/tools/cache.(*ResourceEventHandlerFuncs).OnAdd(0xc420169c60, 0x15770c0, 0xc4208c0ee0)
<autogenerated>:1 +0x62
github.com/rancher/longhorn-manager/vendor/k8s.io/client-go/tools/cache.FilteringResourceEventHandler.OnAdd(0xc420386340, 0x219aa40, 0xc420169c60, 0x15770c0, 0xc4208c0ee0)
/go/src/github.com/rancher/longhorn-manager/vendor/k8s.io/client-go/tools/cache/controller.go:227 +0x6b
github.com/rancher/longhorn-manager/vendor/k8s.io/client-go/tools/cache.(*FilteringResourceEventHandler).OnAdd(0xc420169c80, 0x15770c0, 0xc4208c0ee0)
<autogenerated>:1 +0x62
github.com/rancher/longhorn-manager/vendor/k8s.io/client-go/tools/cache.(*processorListener).run.func1.1(0xc42008f450, 0x0, 0xc420022c00)
/go/src/github.com/rancher/longhorn-manager/vendor/k8s.io/client-go/tools/cache/shared_informer.go:554 +0x23b
github.com/rancher/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/wait.ExponentialBackoff(0x989680, 0x3ff0000000000000, 0x3fb999999999999a, 0x5, 0xc420231df0, 0x18, 0x8b6350)
/go/src/github.com/rancher/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:203 +0x9c
github.com/rancher/longhorn-manager/vendor/k8s.io/client-go/tools/cache.(*processorListener).run.func1()
/go/src/github.com/rancher/longhorn-manager/vendor/k8s.io/client-go/tools/cache/shared_informer.go:548 +0x81
github.com/rancher/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc420642768)
/go/src/github.com/rancher/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x5e
github.com/rancher/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc420231f68, 0xdf8475800, 0x0, 0x13be701, 0xc4205ae900)
/go/src/github.com/rancher/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134 +0xbd
github.com/rancher/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc420642768, 0xdf8475800, 0xc4205ae900)
/go/src/github.com/rancher/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
github.com/rancher/longhorn-manager/vendor/k8s.io/client-go/tools/cache.(*processorListener).run(0xc42046e980)
/go/src/github.com/rancher/longhorn-manager/vendor/k8s.io/client-go/tools/cache/shared_informer.go:546 +0x78
github.com/rancher/longhorn-manager/vendor/k8s.io/client-go/tools/cache.(*processorListener).(github.com/rancher/longhorn-manager/vendor/k8s.io/client-go/tools/cache.run)-fm()
/go/src/github.com/rancher/longhorn-manager/vendor/k8s.io/client-go/tools/cache/shared_informer.go:390 +0x2a
github.com/rancher/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1(0xc4202e0530, 0xc42007d370)
/go/src/github.com/rancher/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:71 +0x4f
created by github.com/rancher/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/wait.(*Group).Start
/go/src/github.com/rancher/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:69 +0x62`

**Comment by andreastoermer** [comment]
Sorry for opening a new one, i saw that someone else have the same problem:

https://github.com/rancher/longhorn/issues/260
