### ISSUE TITLE
A fatal error has occured, this connection is terminated

### ISSUE THREAD

**Issue by ShadowN1ghtmare** [rancher/longhorn#531]
I was playing Minecraft on a Server with my friends, I was just flying around in the nether when is got kicked from the server and now I cant connect anymore, it says "a fatal error has occured, this connection is terminated". I tried reinstalling modpack, restarting pc and my friend restarted server for me. But nothing helped :/ I googled the error but as different sites say so different issues it wasnt rly helping
Im not rly good in reading those crash logs but what i can tell is that i actually connect to the server before it kicks me.
Here the logs from my Client (we use TechnicLauncher for our modpack (Magical Sky Block if you want to have a look at))
[2019-05-13-1.log.gz](https://github.com/rancher/longhorn/files/3178056/2019-05-13-1.log.gz)
[2019-05-13-2.log.gz](https://github.com/rancher/longhorn/files/3178057/2019-05-13-2.log.gz)
[2019-05-14-1.log.gz](https://github.com/rancher/longhorn/files/3178058/2019-05-14-1.log.gz)
[2019-05-14-2.log.gz](https://github.com/rancher/longhorn/files/3178059/2019-05-14-2.log.gz)
[2019-05-14-3.log.gz](https://github.com/rancher/longhorn/files/3178060/2019-05-14-3.log.gz)
[2019-05-14-4.log.gz](https://github.com/rancher/longhorn/files/3178061/2019-05-14-4.log.gz)
[2019-05-14-5.log.gz](https://github.com/rancher/longhorn/files/3178062/2019-05-14-5.log.gz)
[fml-client-1.log](https://github.com/rancher/longhorn/files/3178063/fml-client-1.log)
[fml-client-2.log](https://github.com/rancher/longhorn/files/3178064/fml-client-2.log)
[fml-client-3.log](https://github.com/rancher/longhorn/files/3178065/fml-client-3.log)
[fml-client-latest.log](https://github.com/rancher/longhorn/files/3178066/fml-client-latest.log)
[fml-junk-earlystartup.log](https://github.com/rancher/longhorn/files/3178067/fml-junk-earlystartup.log)
[latest.log](https://github.com/rancher/longhorn/files/3178068/latest.log)

and here the server log files

[2019-05-12-5.log.gz](https://github.com/rancher/longhorn/files/3178085/2019-05-12-5.log.gz)
[2019-05-12-6.log.gz](https://github.com/rancher/longhorn/files/3178086/2019-05-12-6.log.gz)
[2019-05-12-7.log.gz](https://github.com/rancher/longhorn/files/3178087/2019-05-12-7.log.gz)
[2019-05-13-1.log.gz](https://github.com/rancher/longhorn/files/3178088/2019-05-13-1.log.gz)
[2019-05-13-2.log.gz](https://github.com/rancher/longhorn/files/3178089/2019-05-13-2.log.gz)
[fml-junk-earlystartup.log](https://github.com/rancher/longhorn/files/3178090/fml-junk-earlystartup.log)
[fml-server-1.log](https://github.com/rancher/longhorn/files/3178091/fml-server-1.log)
[fml-server-2.log](https://github.com/rancher/longhorn/files/3178092/fml-server-2.log)
[fml-server-3.log](https://github.com/rancher/longhorn/files/3178093/fml-server-3.log)

[Uploading latest.log…]()
[Uploading 2019-05-10-1.log.gz…]()
[Uploading 2019-05-10-2.log.gz…]()
[Uploading 2019-05-10-3.log.gz…]()
[Uploading 2019-05-10-4.log.gz…]()
[Uploading 2019-05-10-5.log.gz…]()
[Uploading 2019-05-11-1.log.gz…]()
[Uploading 2019-05-12-1.log.gz…]()
[Uploading 2019-05-12-2.log.gz…]()
[Uploading 2019-05-12-3.log.gz…]()
[Uploading 2019-05-12-4.log.gz…]()

Hopefully smb can help me, if I forget anything pls tell me

**Comment by ShadowN1ghtmare** [comment]
I think those lines should tell what the issue is , but I dont understand it
[19:43:28] [Server thread/INFO]: ShadowN1ghtmare[/62.224.240.179:51900] logged in with entity id 95464 at (146.24548705081068, 42.015623522335375, 95.89720035207029)
[19:43:28] [Server thread/INFO]: ShadowN1ghtmare joined the game
[19:43:28] [Server thread/ERROR]: "Silently" catching entity tracking error.
net.minecraft.util.ReportedException: Adding entity to track
	at net.minecraft.entity.EntityTracker.func_72785_a(EntityTracker.java:230) [mn.class:?]
	at cpw.mods.fml.common.registry.EntityRegistry.tryTrackingEntity(EntityRegistry.java:364) [EntityRegistry.class:?]
	at net.minecraft.entity.EntityTracker.func_72786_a(EntityTracker.java:61) [mn.class:?]
	at net.minecraft.world.WorldManager.func_72703_a(SourceFile:31) [mp.class:?]
	at net.minecraft.world.World.func_72923_a(World.java:1347) [ahb.class:?]
	at net.minecraft.world.WorldServer.func_72923_a(WorldServer.java:844) [mt.class:?]
	at net.minecraft.world.World.func_72868_a(World.java:3304) [ahb.class:?]
	at net.minecraft.world.chunk.Chunk.func_76631_c(Chunk.java:921) [apx.class:?]
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:46) [ChunkIOProvider.class:?]
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:12) [ChunkIOProvider.class:?]
	at net.minecraftforge.common.util.AsynchronousExecutor$Task.finish(AsynchronousExecutor.java:189) [AsynchronousExecutor$Task.class:?]
	at net.minecraftforge.common.util.AsynchronousExecutor.finishActive(AsynchronousExecutor.java:354) [AsynchronousExecutor.class:?]
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.tick(ChunkIOExecutor.java:30) [ChunkIOExecutor.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:596) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
Caused by: java.lang.IllegalStateException: Entity is already tracked!
	at net.minecraft.entity.EntityTracker.func_72785_a(EntityTracker.java:196) ~[mn.class:?]
	... 17 more
[19:43:45] [Server thread/INFO]: ShadowN1ghtmare lost connection: TextComponent{text='Disconnected', siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null}}
[19:43:45] [Server thread/INFO]: ShadowN1ghtmare left the game
[20:31:16] [User Authenticator #2/INFO]: UUID of player ShadowN1ghtmare is 0ebd9cb8-612f-4691-bec5-96afc7794976

**Comment by yasker** [comment]
@ShadowN1ghtmare  I think you're in the wrong project...
